//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dlgv32.rc
//
#define IDC_GEOTIFF_PROJECTION          2
#define IDD_ABOUTBOX                    100
#define ID_CURRENT_TOOL                 101
#define ID_MOUSE_POS_UTM                102
#define ID_MOUSE_POS_LATLONG            103
#define IDR_MAINFRAME                   128
#define IDR_DLGV32TYPE                  129
#define IDD_LOADING_DIALOG              130
#define IDD_MAIN_PROPERTIES_DIALOG      132
#define IDD_PICK_DIALOG                 135
#define IDI_FINGER                      137
#define IDD_DLGO_CATEGORY_DIALOG        137
#define IDD_DLG_OPTIONS                 138
#define IDI_MAGNIFY                     140
#define IDI_CURSOR                      141
#define IDI_EARTH                       143
#define IDD_DISTANCE                    144
#define IDI_CONTROL_CENTER              145
#define IDB_BITMAP1                     146
#define IDD_RASTER_OPTIONS              147
#define IDD_CLIPPING_REGION_SELECTOR    149
#define IDC_PAN_CURSOR                  150
#define IDC_ZOOM_CURSOR                 151
#define IDC_X_CURSOR                    152
#define IDC_POLY_SELECTOR_CURSOR        153
#define IDD_COLOR_PICKER                157
#define IDD_EASTEREGG                   158
#define IDD_SDTS_LAYER_DIALOG           161
#define IDD_SDTSDLG_IDEN                162
#define IDD_SDTSDLG_STAT                163
#define IDD_SDTSDLG_DATAQUALITY         165
#define IDD_TIFF_METADATA               166
#define IDD_GEOTIFF_METADATA            167
#define IDD_DLGO_HEADERINFO             168
#define IDD_DLGO_CONTROLPOINTS          169
#define IDD_SDTSDLG_AHDR                170
#define IDD_DAYLIGHT_SHADER             173
#define IDD_GRADIENT_SHADER_OPTIONS     174
#define IDD_VERTICAL_OPTIONS            176
#define IDD_SHADER_OPTIONS              177
#define IDD_TEXTURE_MAPPED_SELECTOR     178
#define IDD_GEOTIFF_VERTICAL_METADATA   179
#define IDD_RASTER_METADATA             180
#define IDD_OVERLAY_TYPE_SELECTOR       182
#define IDC_PROGRESS1                   1000
#define IDC_NODE_SHAPE_CIRCLE           1001
#define IDC_OVERLAY_LIST                1001
#define IDC_OVERLAYS_TO_CLIP_LIST       1001
#define IDC_TRANS_COLOR_LIST            1001
#define IDC_NODE_SHAPE_SQUARE           1002
#define IDC_PROPERTIES_BUTTON           1003
#define IDC_NODE_SHAPE_TRIANGLE         1003
#define IDC_OPTIONS_BUTTON              1004
#define IDC_AREA_SHAPE_CIRCLE           1004
#define IDC_CLOSE_OVERLAY               1005
#define IDC_AREA_SHAPE_SQUARE           1005
#define IDC_AREA_SHAPE_TRIANGLE         1006
#define IDC_ELEMENT_ID                  1007
#define IDC_LINE_COLOR                  1007
#define IDC_ELEMENT_TYPE                1008
#define IDC_ATT_CODE_LIST               1011
#define IDC_PICK_DCU_NAME               1013
#define IDC_PICK_CATEGORY               1014
#define IDC_SHOW_OVERLAY                1026
#define ID_STATIC                       1029
#define IDC_HIDE_NODES_OVERLAY          1030
#define IDC_HIDE_AREAS_OVERLAY          1031
#define IDC_HIDE_NODES_ALL              1031
#define IDC_HIDE_AREAS_ALL              1032
#define IDC_HIDE_LINES_OVERLAY          1032
#define IDC_METERS                      1033
#define IDC_KILOMETERS                  1034
#define IDC_FEET                        1035
#define IDC_Miles                       1036
#define IDC_DISTANCE                    1037
#define IDC_CLOSE_PICK_DIALOG           1038
#define IDC_HIDE_LINES_ALL              1039
#define IDC_RASTER_OPTIONS_INTENSITY    1040
#define IDC_RASTER_OPTIONS_DEFAULT_INTENSITY 1041
#define IDC_SELECT_ALL_OVERLAYS         1046
#define IDC_DESELECT_ALL                1047
#define IDC_RASTER_OPTIONS_TRANSPARENT  1048
#define IDC_REMOVE_CLIPS                1049
#define IDC_PHOTOMETRIC_INTERP          1050
#define IDC_BITS_PER_SAMPLE             1051
#define IDC_TIFF_LENGTH                 1052
#define IDC_TIFF_WIDTH                  1053
#define IDC_ROWS_PER_STRIP              1054
#define IDC_TIFF_DESCRIPTION            1055
#define IDC_TIFF_DATETIME               1056
#define IDC_TIFF_COPYRIGHT              1057
#define IDC_COMBO_MODE                  1059
#define IDC_RADIO3                      1061
#define IDC_RADIO4                      1062
#define IDC_RASTER_OPTIONS_TRANS_COLOR  1062
#define IDC_RADIO5                      1063
#define IDC_DLG_LINE_WIDTH              1063
#define IDC_RADIO6                      1064
#define IDC_GEOTIFF_PCSCITATION         1087
#define IDC_GEOTIFF_GEOTIEPOINT         1088
#define IDC_GEOTIFF_GEOPIXELSCALE       1089
#define IDC_LAYER_LIST                  1098
#define IDC_SDTDDLG_IDEN_STANDARDID     1099
#define IDC_SDTSDLG_IDEN_STANDARDVER    1100
#define IDC_SDTSDLG_IDEN_STANDARDDOCREF 1101
#define IDC_SDTSDLG_IDEN_PROFILEID      1102
#define IDC_SDTSDLG_IDEN_PROFILEVER     1103
#define IDC_SDTSDLG_IDEN_PROFILEDOCREF  1104
#define IDC_SDTSDLG_IDEN_TITLE          1105
#define IDC_SDTSDLG_IDEN_DATAID         1106
#define IDC_SDTSDLG_IDEN_MAPDATE        1107
#define IDC_SDTSDLG_IDEN_CREATIONDATE   1108
#define IDC_SDTSDLG_IDEN_DATASTRUCT     1109
#define IDC_SDTSDLG_IDEN_SCALE          1110
#define IDC_SDTSDLG_IDEN_COMPOSITES     1111
#define IDC_SDTSDLG_IDEN_VECTORGEOMETRY 1112
#define IDC_SDTSDLG_IDEN_VECTORTOPOLOGY 1113
#define IDC_SDTSDLG_IDEN_RASTER         1114
#define IDC_SDTSDLG_IDEN_FEATURESLEVEL  1115
#define IDC_SDTSDLG_STAT_NUMAREAS       1115
#define IDC_SDTSDLG_IDEN_EXTSPATIALREF  1116
#define IDC_SDTSDLG_STAT_NONODES        1116
#define IDC_SDTSDLG_STAT_NODEGLINES     1117
#define IDC_SDTSDLG_STAT_NOLINES        1118
#define IDC_SDTSDLG_STAT_NOPOLYGONS     1119
#define IDC_SDTSDLG_DQAA                1120
#define IDC_SDTSDLG_DQCG                1121
#define IDC_GEOTIFF_MODELTYPE           1121
#define IDC_SDTSDLG_DQHL                1122
#define IDC_GEOTIFF_RASTERTYPE          1122
#define IDC_DLGO_DCU_NAME               1122
#define IDC_SDTSDLG_DQLC                1123
#define IDC_DLGO_SOURCE_DATE            1123
#define IDC_SDTSDLG_DQPA                1124
#define IDC_DLGO_DATE_QUALIFIER         1124
#define IDC_DLGO_SOURCE_SCALE           1125
#define IDC_DLGO_LEVEL_CODE             1126
#define IDC_DLGO_RESOLUTION             1130
#define IDC_DLGO_VDATUM                 1132
#define IDC_DLGO_BANNER                 1133
#define IDC_DLGO_CONTROLPOINT_ID        1134
#define IDC_DLGO_CONTROLPOINT_LABEL     1135
#define IDC_DLGO_CONTROLPOINT_LATITUDE  1136
#define IDC_DLGO_CONTROLPOINT_LONGITUDE 1137
#define IDC_DLGO_CONTROLPOINT_X         1138
#define IDC_DLGO_CONTROLPOINT_Y         1139
#define IDC_DLGO_CONTROLPOINT_SPIN      1140
#define IDC_DLGO_CONTROLPOINT_NUMBER    1141
#define IDC_DLGO_CATEGORY_ID            1142
#define IDC_DLGO_CATEGORY_NAME          1143
#define IDC_DLGO_FORMAT_CODES           1144
#define IDC_DLGO_NODES_REFERENCED       1145
#define IDC_DLGO_ACTUAL_NODES           1146
#define IDC_DLGO_AREAS_REF              1147
#define IDC_DLGO_ACTUAL_AREAS           1148
#define IDC_DLGO_LINES_REF              1149
#define IDC_DLGO_ACTUAL_LINES           1150
#define IDC_DLGO_NA_LINKAGE             1151
#define IDC_DLGO_NL_LINKAGE             1152
#define IDC_DLGO_AN_LINKAGE             1153
#define IDC_DLGO_AL_LINKAGE             1154
#define IDC_DLGO_AREA_COORD_LIST        1155
#define IDC_DLGO_LINE_COORD_LIST        1156
#define IDC_ENTITY_DESC                 1158
#define IDC_SDTSDLG_AHDR_PAIRS          1159
#define IDC_SDTSDLG_AHDR_BANNER         1161
#define IDC_DAYLIGHT_SHADER_WATER_LEVEL 1163
#define IDC_DAYLIGHT_SHADER_WATER_ALPHA 1164
#define IDC_DAYLIGHT_SHADER_SURFACE_COLOR 1165
#define IDC_DAYLIGHT_SHADER_WATER_COLOR 1166
#define IDC_DAYLIGHT_SHADER_WATER_ON    1167
#define IDC_GRADIENT_SHADER_LOW_COLOR   1168
#define IDC_GRADIENT_SHADER_HIGH_COLOR  1169
#define IDC_SHADER_OPTIONS_GRADIENT_SET_LO_COLOR 1169
#define IDC_DAYLIGHT_SHADER_WATER_LEVEL_TEXT 1170
#define IDC_SHADER_OPTIONS_GRADIENT_SET_HI_COLOR 1170
#define IDC_DAYLIGHT_SHADER_ALPHA_TEXT  1171
#define IDC_DAYLIGHT_SHADER_ALTITUDE    1172
#define IDC_DAYLIGHT_SHADER_ALTITUDE_SPINNER 1173
#define IDC_DAYLIGHT_SHADER_AZIMUTH     1174
#define IDC_DAYLIGHT_SHADER_AZIMUTH_SPINNER 1175
#define IDC_VERTICAL_OPTIONS_SHADER     1177
#define IDC_VERTICAL_OPTIONS_ALTITUDE   1178
#define IDC_VERTICAL_OPTIONS_ALTITUDE_SPINNER 1179
#define IDC_VERTICAL_OPTIONS_AZIMUTH    1180
#define IDC_VERTICAL_OPTIONS_AZIMUTH_SPINNER 1181
#define IDC_VERTICAL_OPTIONS_WATER_LEVEL 1182
#define IDC_VERTICAL_OPTIONS_WATER_LEVEL_TEXT 1183
#define IDC_VERTICAL_OPTIONS_WATER_ALPHA 1184
#define IDC_VERTICAL_OPTIONS_WATER_COLOR 1185
#define IDC_VERTICAL_OPTIONS_WATER_ON   1186
#define IDC_VERTICAL_OPTIONS_ENABLE_LIGHTING 1187
#define IDC_VERTICAL_OPTIONS_AMBIENT_LIGHT 1188
#define IDC_SHADER_OPTIONS_DAYLIGHT_SURFACE_COLOR 1188
#define IDC_RASTER_INTERPOLATE          1189
#define IDC_VERTICAL_OPTIONS_VERT_EXAG  1189
#define IDC_TEXTURE_MAPPED_LAYERS_LIST  1190
#define IDC_GEOTIFF_VERTICAL_DATUM      1192
#define IDC_GEOTIFF_MAX_ELEVATION       1193
#define IDC_GEOTIFF_VERTICAL_CITATION   1194
#define IDC_GEOTIFF_VERTICAL_UNITS      1195
#define IDC_GEOTIFF_MIN_ELEVATION       1196
#define IDC_RASTER_MIN_ELEVATION_LABEL  1197
#define IDC_RASTER_MAX_ELEVATION_LABEL  1198
#define IDC_RASTER_DESCRIPTION          1199
#define IDC_RASTER_MAX_ELEVATION        1201
#define IDC_RASTER_VERTICAL_UNITS       1202
#define IDC_RASTER_MIN_ELEVATION        1203
#define IDC_RASTER_HEIGHT               1204
#define IDC_RASTER_WIDTH                1205
#define IDC_RASTER_VERTICAL_UNITS_LABEL 1207
#define IDC_RASTER_PROJECTION           1209
#define IDC_SDTSDLG_IDEN_PROJECTION     1213
#define IDC_RASTER_TEXTURE_MAP          1214
#define IDC_SHADER_OPTIONS_HSV_LOW_COLOR_START 1218
#define IDC_SHADER_OPTIONS_HSV_VALUE    1219
#define IDC_SHADER_OPTIONS_HSV_SATURATION 1220
#define IDC_SHADER_OPTIONS_HSV_RANGE    1221
#define IDC_OVERLAY_TYPE_LIST           1222
#define IDC_DLGO_HEADER_PROJECTION      1223
#define ID_FILE_OPEN_NEW                32771
#define ID_FILE_OPEN_CURRENT            32772
#define ID_FILE_UNLOAD_ALL              32773
#define ID_TOOLS_ZOOM                   32774
#define ID_TOOLS_PAN                    32775
#define ID_ZOOM_IN                      32780
#define ID_ZOOM_OUT                     32781
#define ID_VIEW_FULLVIEW                32782
#define ID_TOOLS_DISTANCE               32783
#define ID_TOOLS_PICK                   32785
#define ID_TOOLS_CONTROLCENTER          32786
#define ID_BG_COLOR                     32787
#define ID_TOOLS_POLYREGION             32790
#define ID_EXPORT_GEOTIFF               32793
#define IDS_REGISTRY_PATH               57671

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1229
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
